### ISSUE TITLE
demo.py crashes

### ISSUE THREAD

**Issue by jengelman** [mattjj/pyhsmm-autoregressive#15]
Running the demo gives the following error:

```
Traceback (most recent call last):
  File "/Users/joshengelman/Documents/src/autoregressive/examples/demo.py", line 41, in <module>
    truemodel.plot()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyhsmm/models.py", line 256, in plot
    sp1_artists = self.plot_observations(feature_ax,plot_slice=plot_slice,update=update)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyhsmm/models.py", line 296, in plot_observations
    scatter_artists = self._plot_2d_data_scatter(ax,state_colors,plot_slice,update)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autoregressive/models.py", line 98, in _plot_2d_data_scatter
    for s, data in zip(self.states_list,self.datas):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autoregressive/models.py", line 89, in datas
    return [undo_AR_striding(s.data,self.nlags) for s in self.states_list]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autoregressive/util.py", line 25, in undo_AR_striding
    strides=(strided_data.shape[1]/(nlags+1)*sz,sz))
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/stride_tricks.py", line 102, in as_strided
    array = np.asarray(DummyArray(interface, base=x))
  File "/usr/local/lib/python2.7/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: 'float' object cannot be interpreted as an index
```

**Comment by bccho** [comment]
What version of numpy are you using? I believe there is a known issue where numpy deprecated float indices starting with 1.12: https://github.com/rbgirshick/py-faster-rcnn/issues/481

**Comment by jengelman** [comment]
@bccho I'm running 1.13, but I was surprised to find the error since I can run all of the examples in base pyhsmm without a problem.

**Comment by bccho** [comment]
@jengelman Actually, I can't replicate your error, even with numpy 1.13
Can you try this on a fresh Python environment? It looks like you're using the Mac framework version of Python.
For reference, I'm using Anaconda3 4.3.21 and Python 2.7.13:
```bash
conda create -n testenv -y python=2.7 anaconda
source activate testenv
# for replicability, install 1.13
conda install -y numpy=1.13
pip install future
pip install pyhsmm
```
Then, I ran `run examples/demo.py` in `ipython` because my Matplotlib backend doesn't play nice with my terminal if I run it using just `python examples/demo.py`.

Let me know what happens when you do this.

**Comment by jengelman** [comment]
@bccho Same thing happens.  The model completes resampling, a blank matplotlib window appears, and then it crashes.

**Comment by bccho** [comment]
Are you using the native `pip` installer for your packages, or did you start using Anaconda?
Perhaps it is a version issue with some other packages, like Matplotlib. What does `python -c "import matplotlib; print matplotlib.__version__"` give you?
For reference, here is my package list:
```
# packages in environment at /Users/bccho/anaconda3/envs/test27:
#
anaconda                  custom                   py27_0
appnope                   0.1.0                    py27_0
backports                 1.0                      py27_0
cycler                    0.10.0                    <pip>
decorator                 4.0.11                   py27_0
enum34                    1.1.6                    py27_0
functools32               3.2.3.post2               <pip>
future                    0.16.0                    <pip>
get_terminal_size         1.0.0                    py27_0
ipython                   5.3.0                    py27_0
ipython_genutils          0.2.0                    py27_0
matplotlib                2.0.2                     <pip>
mkl                       2017.0.3                      0
nose                      1.3.7                     <pip>
numpy                     1.13.0                   py27_0
openssl                   1.0.2l                        0
path.py                   10.3.1                   py27_0
pathlib2                  2.2.1                    py27_0
pexpect                   4.2.1                    py27_0
pickleshare               0.7.4                    py27_0
pip                       9.0.1                    py27_1
prompt_toolkit            1.0.14                   py27_0
ptyprocess                0.5.1                    py27_0
pybasicbayes              0.2.2                     <pip>
pygments                  2.2.0                    py27_0
pyhsmm                    0.1.7                     <pip>
pyparsing                 2.2.0                     <pip>
python                    2.7.13                        0
python-dateutil           2.6.0                     <pip>
pytz                      2017.2                    <pip>
readline                  6.2                           2
scandir                   1.5                      py27_0
scipy                     0.19.1                    <pip>
setuptools                27.2.0                   py27_0
simplegeneric             0.8.1                    py27_1
six                       1.10.0                   py27_0
six                       1.10.0                    <pip>
sqlite                    3.13.0                        0
subprocess32              3.2.7                     <pip>
tk                        8.5.18                        0
traitlets                 4.3.2                    py27_0
wcwidth                   0.1.7                    py27_0
wheel                     0.29.0                   py27_0
zlib                      1.2.8                         3
```

**Comment by jengelman** [comment]
@bccho I'm also running matplotlib 2.0.2, installed using native pip.

**Comment by bccho** [comment]
I'm afraid I can't help you until I can replicate the error. Can you comment with the output of `pip list`?

**Comment by jengelman** [comment]
Just started using virtualenvs, so my environment is kinda a mess:

```alabaster (0.7.9)
amqp (2.1.4)
anaconda-client (1.6.3)
anaconda-navigator (1.6.2)
anaconda-project (0.6.0)
appnope (0.1.0)
appscript (1.0.1)
asn1crypto (0.22.0)
astroid (1.4.9)
astropy (1.3.2)
autoregressive (0.1.1)
Babel (2.3.4)
backports-abc (0.5)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.5.0.1)
beautifulsoup4 (4.6.0)
billiard (3.5.0.2)
bitarray (0.8.1)
blaze (0.10.1)
bleach (1.5.0)
bokeh (0.12.5)
boto (2.46.1)
Bottleneck (1.2.1)
cdecimal (2.3)
celery (4.0.2)
cffi (1.10.0)
chardet (3.0.3)
click (6.7)
cloudpickle (0.2.2)
clyent (1.2.2)
colorama (0.3.9)
CommonMark (0.5.4)
configparser (3.5.0)
contextlib2 (0.5.5)
cryptography (1.8.1)
cycler (0.10.0)
Cython (0.25.2)
cytoolz (0.8.2)
dask (0.14.3)
datacleaner (0.1.5)
datashape (0.5.4)
decorator (4.0.11)
distributed (1.16.3)
docutils (0.13.1)
entrypoints (0.2.2)
enum (0.4.6)
enum34 (1.1.6)
et-xmlfile (1.0.1)
fastcache (1.0.2)
filterpy (0.1.5)
Flask (0.12.2)
Flask-Cors (3.0.2)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
future (0.16.0)
futures (3.1.1)
gevent (1.2.1)
greenlet (0.4.12)
grin (1.2.1)
gym (0.5.6)
h5py (2.6.0)
HeapDict (1.0.0)
hmmlearn (0.2.0)
html5lib (0.999)
hyperopt (0.1)
idna (2.5)
imagesize (0.7.1)
imbalanced-learn (0.2.1)
ipaddress (1.0.18)
ipykernel (4.5.2)
ipython (5.3.0)
ipython-genutils (0.2.0)
ipywidgets (5.2.2)
isort (4.2.5)
itsdangerous (0.24)
jdcal (1.3)
jedi (0.10.2)
Jinja2 (2.8)
joblib (0.10.3)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.2.1)
kombu (4.0.2)
lazy-object-proxy (1.2.2)
llvmlite (0.16.0)
locket (0.2.0)
lxml (3.7.3)
MarkupSafe (0.23)
matplotlib (2.0.2)
mistune (0.7.3)
mlpy (0.1.0)
mlxtend (0.5.0)
mock (2.0.0)
mpmath (0.19)
msgpack-python (0.4.8)
multipledispatch (0.4.9)
navigator-updater (0.1.0)
nbconvert (4.2.0)
nbformat (4.2.0)
nbsphinx (0.2.11)
networkx (1.11)
nltk (3.2.2)
nose (1.3.7)
notebook (4.3.1)
numba (0.33.0+0.ge79330a.dirty)
numexpr (2.6.1)
numpy (1.13.0)
numpydoc (0.6.0)
odo (0.5.0)
olefile (0.44)
openpyxl (2.4.7)
packaging (16.8)
pandas (0.20.2)
pandas-datareader (0.2.1)
pandocfilters (1.4.1)
partd (0.3.8)
pathlib2 (2.2.1)
patsy (0.4.1)
pep8 (1.7.0)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (4.0.0)
pip (9.0.1)
ply (3.10)
prompt-toolkit (1.0.14)
psutil (5.2.2)
ptyprocess (0.5.1)
py (1.4.33)
PyAudio (0.2.7)
pybasicbayes (0.2.2)
PyBayes (0.3-post-nongit)
pycosat (0.6.2)
pycparser (2.17)
pycrypto (2.6.1)
pycurl (7.43.0)
pyflakes (1.5.0)
pyglet (1.2.4)
Pygments (2.2.0)
pyhsmm (0.1.7)
pylint (1.6.4)
pymc3 (3.0rc4)
pymongo (3.4.0)
pyodbc (4.0.16)
pyOpenSSL (17.0.0)
pyparsing (2.1.4)
pytest (3.0.7)
python-dateutil (2.6.0)
pytools (2016.2.6)
pytz (2017.2)
PyWavelets (0.5.2)
PyYAML (3.12)
pyzmq (16.0.2)
QtAwesome (0.4.4)
qtconsole (4.2.1)
QtPy (1.2.1)
recommonmark (0.4.0)
requests (2.14.2)
requests-file (1.4.1)
rope (0.9.4)
scandir (1.5)
scikit-image (0.13.0)
scikit-learn (0.18.1)
scipy (0.18.1)
seaborn (0.7.1)
setuptools (32.1.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
sortedcollections (0.5.3)
sortedcontainers (1.5.7)
Sphinx (1.5.1)
spyder (3.1.4)
SQLAlchemy (1.1.9)
statsmodels (0.8.0)
subprocess32 (3.2.7)
sympy (1.0)
tables (3.3.0)
tblib (1.3.2)
terminado (0.6)
testpath (0.3)
Theano (0.8.2)
toolz (0.8.2)
tornado (4.4.2)
tqdm (4.10.0)
traitlets (4.3.2)
unicodecsv (0.14.1)
update-checker (0.16)
vine (1.1.3)
vowpalwabbit (8.2.1)
wcwidth (0.1.7)
Werkzeug (0.12.2)
wheel (0.29.0)
widgetsnbextension (1.2.6)
wrapt (1.10.10)
xgbfir (0.2)
xgboost (0.6a2)
xlrd (1.0.0)
XlsxWriter (0.9.6)
xlwings (0.10.4)
xlwt (1.2.0)
zict (0.1.2)

**Comment by bccho** [comment]
As per my first suggestion, can you create a new environment (`virtualenv env && source env/bin/activate`) and try install everything you need from scratch?

**Comment by jengelman** [comment]
Same result as installing in a conda virtualenv or without a virtualenv at all, runs fine until the plotting, and then crashes due to float indexes.  Pyhsmm files continue to work fine, still only autoregressive having issues.

**Comment by bccho** [comment]
I think part of the confusion is that you are using anaconda but alternating between package managers when that's not necessary. Activate your new conda environment, type `conda list` and compare with my output above. To get the same results you should also `conda install ipython`

I think something suspicious is going on between your installed packages. Let me know what differences you find.

**Comment by jengelman** [comment]
Differences:

functools32  3.2.3.2, you have 3.2.3.post2
pyparsing 2.1.4, you have 2.2.0

Curiously, running conda upgrade on these packages doesn't do anything.

Additionally, matplotlib is listed as np113py27_0  instead of just py27_0, not quite sure what that means.  

All of my other installed packages are identical to yours.  Running the script with ipython gives the same results as running with regular python.

**Comment by bccho** [comment]
Sorry, I have been out for the past two weeks.

I'm still unable to replicate your error. Can you provide the following:
* your OS and OS version
* the output of `conda -V`
* a list of `bash` commands that replicably produce your problem, starting from creating a new conda environment?

**Comment by jengelman** [comment]
OS: OSX 10.12.6
conda: conda 4.3.23


Commands:
```
conda create --name autoregressive
pip install autoregressive
python demo.py
```
Same thing happens when building from source, could be an issue with the OSX port of numpy.

**Comment by bccho** [comment]
Note that you need to activate the environment with `source activate autoregressive`. Also note that simply creating an environment won't install the required packages. Try `conda create --name autoregressive anaconda` or manually installing the packages you need.

Also, the version of Autoregressive on PyPI is (the last time I checked) outdated, so you should clone this repository and run the demo from the repository's root directory, or call `pip install -e .` from the repo's root directory to install it in your site packages.

I am running OS X 10.12.5 so I doubt it is a problem with the OS X port of numpy. For reference, my conda version is 4.3.21

The following commands have worked on my machine with both python=2.7 and python=3.5
```bash
conda create -n testenv -y python=2.7 anaconda
source activate testenv
# for replicability, install 1.13
conda install -y numpy=1.13
pip install future
pip install pyhsmm

cd /path/to/cloned/autoregressive/repo
ipython
run examples/demo.py
```

**Comment by jengelman** [comment]
@bccho That worked, thanks!  Guess it was just the version from pip.

**Comment by bccho** [comment]
This error is different from the original issue and it can be fixed by modifying `inb-demo.py` directly.

Notice that the float/index error occurs on line 46, where the size of a numpy array is given with `10.`, which is interpreted as a float. This is illegal in new versions of numpy. Remove the decimal point to fix the error.

You will find that there is a second error later in line 70 of the same script that occurs because the model's `stateseq`s are a few elements shorter than the original data. Wrap each boolean expression in `np.nonzero` to fix this error.

See [my fork](https://github.com/bccho/pyhsmm-autoregressive/blob/master/examples/inb-demo.py) for the applied changes.
