### ISSUE TITLE
Simple fix to get working with Python 3.6 (on MacOS)

### ISSUE THREAD

**Issue by jmarkow** [mattjj/pyhsmm-autoregressive#16]
Maybe I'm doing something funky here, but to get this working appropriately on my machine with Python 3.6 I had to change  [the line linked here](https://github.com/mattjj/pyhsmm-autoregressive/blob/master/autoregressive/models.py#L240) to,

```python
 from autoregressive.messages import resample_arhmm
```

If I don't make this change I get the following error when resampling a model,

```bash
Traceback (most recent call last):                                                                                                                           
  File "/Users/jmarkow/anaconda/envs/moseq2_model_python3/bin/moseq2-model", line 11, in <module>
    load_entry_point('moseq2-model', 'console_scripts', 'moseq2-model')()
  File "/Users/jmarkow/anaconda/envs/moseq2_model_python3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jmarkow/anaconda/envs/moseq2_model_python3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/jmarkow/anaconda/envs/moseq2_model_python3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jmarkow/anaconda/envs/moseq2_model_python3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jmarkow/anaconda/envs/moseq2_model_python3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/jmarkow/Development/python/moseq2_model/moseq2_model/cli.py", line 214, in learn_model
    file=sys.stdout)
  File "/Users/jmarkow/Development/python/moseq2_model/moseq2_model/train/util.py", line 19, in train_model
    model.resample_model(num_procs)
  File "/Users/jmarkow/anaconda/envs/moseq2_model_python3/lib/python3.6/site-packages/pyhsmm/models.py", line 442, in resample_model
    self.resample_states(num_procs=num_procs)
  File "/Users/jmarkow/anaconda/envs/moseq2_model_python3/lib/python3.6/site-packages/autoregressive/models.py", line 240, in resample_states
    from messages import resample_arhmm
ModuleNotFoundError: No module named 'messages'
```

I also tested this change with a Python 2.7 environment and it didn't introduce any additional issues.  Seems like a harmless change on my end.

**Comment by slinderman** [comment]
Thanks, @jmarkow -- I pushed a fix in https://github.com/mattjj/pyhsmm-autoregressive/commit/19899d5531ae6222111e5881ddbf8e51b4d2da7e
